/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Affix: typeof import('./src/components/Affix.vue')['default']
    CommitLog: typeof import('./src/components/CommitLog.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    LangMenu: typeof import('./src/components/LangMenu.vue')['default']
    ListScroll: typeof import('./src/components/ListScroll.vue')['default']
    LoadingOverlay: typeof import('./src/components/LoadingOverlay.vue')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    Project: typeof import('./src/components/Project.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignInDialog: typeof import('./src/components/SignInDialog.vue')['default']
    SignUpDialog: typeof import('./src/components/SignUpDialog.vue')['default']
    SnackbarQueue: typeof import('./src/components/SnackbarQueue.vue')['default']
    ThemeButton: typeof import('./src/components/ThemeButton.vue')['default']
    Unit: typeof import('./src/components/Unit.vue')['default']
    UserButton: typeof import('./src/components/UserButton.vue')['default']
  }
}
