/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Affix: typeof import('./src/components/Affix.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    LoadingOverlay: typeof import('./src/components/LoadingOverlay.vue')['default']
    Project: typeof import('./src/components/Project.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignInDialog: typeof import('./src/components/SignInDialog.vue')['default']
    SignUpDialog: typeof import('./src/components/SignUpDialog.vue')['default']
    Snackbar: (typeof import("./src/components/Snackbar.vue"))["default"]
    Unit: typeof import('./src/components/Unit.vue')['default']
  }
}
