/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Editor: typeof import('./src/components/Editor.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Project: typeof import('./src/components/Project.vue')['default']
    ProjectList: typeof import('./src/components/ProjectList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Unit: typeof import('./src/components/Unit.vue')['default']
  }
}
